apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: zass35453-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: zass35453-go 
  name: zass35453-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: zass35453-go 
